/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "unity.h"
#include "stdio.h"

extern void initialise_monitor_handles(void);

void setUp() {
  printf("setUp my_test\n");
}

void tearDown() {
  printf("tearDown my_test\n");
}

void testWillAlwaysPass(void) {
  TEST_ASSERT_EQUAL_INT(42,42);
}

void xxtestWillAlwaysFail(void) {
  TEST_ASSERT_EQUAL_INT(42,1);
}

void resetTest(void)
{
  tearDown();
  setUp();
}

int main(void)
{
	initialise_monitor_handles();
	UnityBegin("..\\Test\\my_test.c");
	RUN_TEST(testWillAlwaysPass, 13);
	RUN_TEST(testWillAlwaysPass, 13);
	RUN_TEST(testWillAlwaysPass, 13);
	RUN_TEST(testWillAlwaysPass, 13);
	RUN_TEST(testWillAlwaysPass, 13);
	RUN_TEST(xxtestWillAlwaysFail, 13);
	return (UnityEnd());
}
